name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run apps
      run: |
        cargo run --bin args
        cargo run --bin array
        cargo run --bin boxed
        cargo run --bin call_by_ref
        cargo run --bin clone_drop
        cargo run --bin closure
        cargo run --bin const
        cargo run --bin custom_type
        cargo run --bin datatype
        cargo run --bin derive_debug
        cargo run --bin destruct
        cargo run --bin enum
        cargo run --bin fn
        cargo run --bin for_loop
        cargo run --bin function_demo
        cargo run --bin generic_function
        cargo run --bin generic_struct
        cargo run --bin gpio
        cargo run --bin hashmap
        cargo run --bin heap_alloc
        cargo run --bin hello
        cargo run --bin if-else
        cargo run --bin impl_enum
        cargo run --bin impl_struct
        cargo run --bin iter
        cargo run --bin label
        cargo run --bin linked_list
        cargo run --bin list
        cargo run --bin loop
        cargo run --bin match
        cargo run --bin mod
        cargo run --bin mod2
        cargo run --bin nested_struct
        cargo run --bin number
        cargo run --bin oop
        cargo run --bin panicked
        cargo run --bin parse
        cargo run --bin pointer
        cargo run --bin pointer_loc
        cargo run --bin review_1
        cargo run --bin self_kw
        cargo run --bin slice
        cargo run --bin some_res
        cargo run --bin string
        cargo run --bin stringed
        cargo run --bin struct
        cargo run --bin test.py
        cargo run --bin thread
        cargo run --bin tuple
        cargo run --bin vector
        cargo run --bin while_loop
